name: Update README

on:
  push:
    paths:
      - '**/*.md'  

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run script to update README
        run: python UpdateScript.py

      - name: Commit updated README
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add README.md
          git commit -m "README 업데이트"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/river20s/TIL.git

